export const sidebarLinks = [
    {
        route: "/",
        label: "Home",
        imgUrl: "/icons/Home.svg",
    },
    {
        route: "/properties",
        label: "Buy",
        imgUrl: "/icons/buy.svg",
    },
    {
        route: "/interior",
        label: "Interior",
        imgUrl: "/icons/buy.svg",
    },
    {
        route: "/about",
        label: "About",
        imgUrl: "/icons/buy.svg",
    },
]

export const menuBarOptions = [
    {
        title: "Buy",
        options: [
            {
                option: "Home for sale",
                link: "/properties"
            },
            {
                option: "For sale by owner",
                link: "/properties"
            }
        ]
    },
    {
        title: "Sell",
        options: [
            {
                option: "Home for sale",
                link: "/properties"
            },
            {
                option: "For sale by owner",
                link: "/properties"
            }
        ]
    },
    {
        title: "Rent",
        options: [
            {
                option: "Home for sale",
                link: "/properties"
            },
            {
                option: "For sale by owner",
                link: "/properties"
            }
        ]
    },
]

export const authTabData = [
    {
        value: "signin",
        title: "Sign In",
        description: "Sign In as admin",
    },
    {
        value: "signup",
        title: "SignUp",
        description: "Add new admin",
    },
]

// privacyData.js
export const privacyData = {
    title: "Space2Heaven - Policies",
    lastUpdated: "October 31, 2024",
    introduction: [
        "This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
        "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.",
    ],
    definitions: [
        { term: "Account", description: "A unique account created for You to access our Service or parts of our Service." },
        { term: "Affiliate", description: "An entity that controls, is controlled by or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority." },
        { term: "Company", description: "Space2Haven SP, Thane, Zenia Building, Hiranandani Circle, Hiranandani Business Park, Off Ghodbunder Rd, Thane, Mumbai, MH 400607." },
        { term: "Cookies", description: "Small files placed on Your device by a website, containing details of Your browsing history and usage." },
        { term: "Country", description: "Maharashtra, India" },
        { term: "Device", description: "Any device that can access the Service such as a computer, a cellphone or a digital tablet." },
        { term: "Personal Data", description: "Any information that relates to an identified or identifiable individual." },
        { term: "Service", description: "The Website." },
        { term: "Service Provider", description: "Any natural or legal person who processes the data on behalf of the Company." },
        { term: "Usage Data", description: "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself." },
        { term: "Website", description: "Space2Haven, accessible from www.space2haven.com" },
        { term: "You", description: "The individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." },
    ],
    typesOfDataCollected: {
        personalData: [
            "Email address",
            "First name and last name",
            "Phone number",
            "Usage Data",
        ],
        usageData: {
            description: "Usage Data is collected automatically when using the Service.",
            details: [
                "IP address, browser type, browser version, pages of our Service visited, time and date of visit, time spent on those pages, unique device identifiers, and other diagnostic data.",
                "Information such as device type, mobile device unique ID, IP address of mobile device, mobile operating system, mobile Internet browser type, unique device identifiers, and other diagnostic data when accessed through a mobile device.",
            ],
        },
        trackingTechnologies: [
            {
                type: "Cookies or Browser Cookies",
                description: "A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.",
            },
            {
                type: "Web Beacons",
                description: "Small electronic files (e.g., clear gifs, pixel tags, single-pixel gifs) that permit the Company to count users or track other website statistics.",
            },
        ],
    },
    cookies: {
        description: "We use both Session and Persistent Cookies for various purposes.",
        types: [
            {
                name: "Necessary / Essential Cookies",
                type: "Session Cookies",
                admin: "Us",
                purpose: "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.",
            },
            {
                name: "Cookies Policy / Notice Acceptance Cookies",
                type: "Persistent Cookies",
                admin: "Us",
                purpose: "These Cookies identify if users have accepted the use of cookies on the Website.",
            },
            {
                name: "Functionality Cookies",
                type: "Persistent Cookies",
                admin: "Us",
                purpose: "These Cookies allow us to remember choices You make when You use the Website, providing a more personal experience.",
            },
        ],
    },
    useOfPersonalData: [
        { purpose: "To provide and maintain our Service", description: "including monitoring the usage of our Service." },
        { purpose: "To manage Your Account", description: "Manage Your registration and provide access to functionalities as a registered user." },
        { purpose: "For the performance of a contract", description: "for fulfilling contracts and agreements with Us." },
        // ...other purposes
    ],
    dataSharing: [
        { type: "With Service Providers", description: "We may share personal information with Service Providers to monitor and analyze the use of our Service." },
        { type: "For business transfers", description: "We may share personal information during negotiations or as part of any merger, sale, or acquisition." },
        { type: "With Affiliates", description: "We may share information with affiliates, requiring them to honor this Privacy Policy." },
        // ...other sharing scenarios
    ],
    retentionOfData: {
        description: "We retain Personal Data only as long as necessary to fulfill the purposes outlined in this Privacy Policy.",
        usageRetention: "Usage Data is retained for shorter periods unless required for security, functionality, or legal obligations.",
    },
    transferOfData: {
        description: "Your data may be transferred and processed in locations outside of Your jurisdiction.",
        consentStatement: "Your submission of information represents Your consent to this transfer.",
        securityAssurance: "We ensure adequate controls are in place to secure Your data in any transfer.",
    },
    deletePersonalData: {
        rights: [
            "You have the right to delete or request assistance in deleting Your Personal Data.",
            "You may update, amend, or delete Your information by managing Your account settings or contacting Us.",
        ],
        note: "We may retain certain information when required by law.",
    },
    dataDisclosure: {
        businessTransactions: "Your Personal Data may be transferred as part of a merger, acquisition, or asset sale.",
        lawEnforcement: "We may disclose Your Personal Data if required by law or in response to valid requests by public authorities.",
        legalRequirements: [
            "Comply with a legal obligation",
            "Protect and defend the rights or property of the Company",
            "Prevent or investigate possible wrongdoing",
            "Protect the safety of Service users or the public",
            "Protect against legal liability",
        ],
    },
    dataSecurity: "While we strive to use commercially acceptable means to protect Your Personal Data, we cannot guarantee its absolute security.",
    contact: {
        email: "Hello@Space2haven.com",
        phone: "8976561551",
    },
};

export const dashboardData = [
    {
        link:"/admin/add-property",
        title: "Add Property",
        color: "red",
    },
    {
        link:"/admin/add-property",
        title: "Add Interior",
        color: "blue",
    },
    {
        link:"/properties",
        title: "All Properties",
        color: "emerald",
    },
    {
        link:"/interiors",
        title: "Interiors",
        color: "purple",
    },
]