export const properties = [
    {
        title: "",
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 7,500,000",
        propertyType: "Villa",
        rooms: {
            bedrooms: 4,
            bathrooms: 6,
        },
        description: "Experience luxury living in this stunning villa, featuring expansive gardens, breathtaking ocean views, and elegant interiors designed for comfort and sophistication.",
        location: "Bengaluru",
        address: {
            street: "Harmony Valley Street, Sarjapur",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 560945,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "30x40",
        area: "20,000 Sq. Ft",
        yearBuilt: 2023,
        features: ["Swimming Pool", "Garden", "Private Parking"],
    },
    {
        title: "",
        images: ["https://plus.unsplash.com/premium_photo-1676823547752-1d24e8597047?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 5,200,000",
        propertyType: "Flat",
        rooms: {
            bedrooms: 3,
            bathrooms: 2,
        },
        description: "Modern flat with excellent amenities and spacious interiors.",
        location: "Bengaluru",
        address: {
            street: "MG Road",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 560001,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "25x35",
        area: "1,500 Sq. Ft",
        yearBuilt: 2020,
        features: ["Gym Access", "Covered Parking", "Play Area"],
    },
    {
        title: "",
        images: ["https://plus.unsplash.com/premium_photo-1661908377130-772731de98f6?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 4,800,000",
        propertyType: "House",
        rooms: {
            bedrooms: 3,
            bathrooms: 2,
        },
        description: "Charming house with a beautiful garden and modern amenities.",
        location: "Bengaluru",
        address: {
            street: "Indiranagar",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 560038,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "30x50",
        area: "1,800 Sq. Ft",
        yearBuilt: 2019,
        features: ["Garden", "Garage", "Pet Friendly"],
    },
    {
        title: "",
        images: ["https://plus.unsplash.com/premium_photo-1661908377130-772731de98f6?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 12,000,000",
        propertyType: "Villa",
        rooms: {
            bedrooms: 5,
            bathrooms: 7,
        },
        description: "Luxurious villa with premium amenities and a stunning view.",
        location: "Bengaluru",
        address: {
            street: "Whitefield",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 560066,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "40x60",
        area: "3,500 Sq. Ft",
        yearBuilt: 2023,
        features: ["Swimming Pool", "Terrace", "Private Parking"],
    },
    {
        title: "",
        images: ["/images/default-image.webp"],
        price: "₹ 3,500,000",
        propertyType: "Flat",
        rooms: {
            bedrooms: 2,
            bathrooms: 1,
        },
        description: "Cozy flat in a prime location with essential amenities.",
        location: "Bengaluru",
        address: {
            street: "Jayanagar",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 560041,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "20x30",
        area: "1,200 Sq. Ft",
        yearBuilt: 2021,
        features: ["Balcony", "24/7 Security", "Basement Parking"],
    },
    {
        title: "",
        images: ["https://plus.unsplash.com/premium_photo-1661908377130-772731de98f6?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 9,800,000",
        propertyType: "House",
        rooms: {
            bedrooms: 4,
            bathrooms: 3,
        },
        description: "Elegant house with a spacious layout and modern design.",
        location: "Bengaluru",
        address: {
            street: "Koramangala",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 560034,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "35x50",
        area: "2,200 Sq. Ft",
        yearBuilt: 2022,
        features: ["Garden", "Solar Panels", "Pet Friendly"],
    },
    {
        title: "",
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 15,000,000",
        propertyType: "Villa",
        rooms: {
            bedrooms: 6,
            bathrooms: 8,
        },
        description: "Grand villa with luxurious features and ample living space.",
        location: "Bengaluru",
        address: {
            street: "Nandi Hills",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 562110,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "50x70",
        area: "5,000 Sq. Ft",
        yearBuilt: 2024,
        features: ["Swimming Pool", "Gym", "Home Theatre"],
    },
    {
        title: "",
        images: ["https://plus.unsplash.com/premium_photo-1676823547752-1d24e8597047?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 6,000,000",
        propertyType: "Flat",
        rooms: {
            bedrooms: 3,
            bathrooms: 2,
        },
        description: "Stylish flat with contemporary design and convenient access.",
        location: "Bengaluru",
        address: {
            street: "Bellandur",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 560103,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "25x35",
        area: "1,600 Sq. Ft",
        yearBuilt: 2020,
        features: ["Gym Access", "Rooftop Access", "Covered Parking"],
    },
    {
        title: "",
        images: ["https://plus.unsplash.com/premium_photo-1661908377130-772731de98f6?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 8,500,000",
        propertyType: "House",
        rooms: {
            bedrooms: 5,
            bathrooms: 4,
        },
        description: "Spacious house with modern amenities and a beautiful garden.",
        location: "Bengaluru",
        address: {
            street: "Hennur",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 560043,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "40x60",
        area: "3,200 Sq. Ft",
        yearBuilt: 2022,
        features: ["Garden", "Office Space", "Pet Friendly"],
    },
    {
        title: "",
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 10,000,000",
        propertyType: "Villa",
        rooms: {
            bedrooms: 4,
            bathrooms: 5,
        },
        description: "Beautiful villa with luxurious amenities and stunning views.",
        location: "Bengaluru",
        address: {
            street: "Varthur",
            city: "Bengaluru",
            state: "Karnataka",
            postalCode: 560087,
        },
        serviceType: "buy",
        status: 'available',
        dimensions: "35x50",
        area: "3,000 Sq. Ft",
        yearBuilt: 2023,
        features: ["Swimming Pool", "Garage", "Terrace Garden"],
    }
];
